/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.proyect.views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.proyect.domain.models.Usuario;

/**
 *
 * @author frijol
 */
public class AppView extends javax.swing.JFrame {
    
    // CURRENT USER
    private final Usuario currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppView.class.getName());

    /**
     * Creates new form AppView
     */
    public AppView(Usuario user) {
       // Aseguramos que el usuario no sea nulo antes de construir la vista
        if (user == null) {
            throw new IllegalArgumentException("La AppView requiere un usuario autenticado.");
        }
        
        this.currentUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupWindowClosingBehavior() {
        // Al cerrar la ventana principal, la aplicación debe terminar
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Confirmar antes de cerrar toda la aplicación
                int response = JOptionPane.showConfirmDialog(
                    AppView.this, 
                    "¿Está seguro que desea salir de la aplicación?", 
                    "Confirmar Salida", 
                    JOptionPane.YES_NO_OPTION);
                
                if (response == JOptionPane.YES_OPTION) {
                    System.exit(0); // Termina toda la aplicación
                }
            }
        });
    }
    

    private static class user {

        public user() {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
