/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.proyect.views.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Area;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author frijol
 */
public class NavbarComponent extends javax.swing.JPanel {

    /**
     * Creates new form NavbarComponent
     */
    public NavbarComponent() {
        initComponents();
        setOpaque(false);
    // prefer a darker minimal background
    setBackground(new Color(30,30,30));
    ajustarImagen(jLabel1);
    // install minimal hover and pointer behavior
    installHover(jButton1);
    installHover(jButton2);
    installHover(jButton3);
    installHover(jButton4);
    installHover(jButton5);

    }

    // Simple navigation listener interface
    public static interface NavigationListener {
        void navigateTo(String route);
    }

    private NavigationListener navigationListener;

    public void setNavigationListener(NavigationListener listener) {
        this.navigationListener = listener;
    }

    private void ajustarImagen(javax.swing.JLabel lbl) {
        // 1. Verificamos que el label tenga un tamaño asignado (si no, dará error)
        if (lbl.getWidth() > 0 && lbl.getHeight() > 0) {

            // 2. Obtenemos el icono que pusiste en Diseño
            javax.swing.ImageIcon iconoOriginal = (javax.swing.ImageIcon) lbl.getIcon();

            if (iconoOriginal != null) {
                // 3. Tomamos la imagen y la redimensionamos al TAMAÑO DEL LABEL
                java.awt.Image imagen = iconoOriginal.getImage();
                java.awt.Image imagenRedimensionada = imagen.getScaledInstance(
                        lbl.getWidth(), // Ancho del Label
                        lbl.getHeight(), // Alto del Label
                        java.awt.Image.SCALE_SMOOTH // Suavizado para que no se vea fea
                );

                // 4. Se la devolvemos al label
                lbl.setIcon(new javax.swing.ImageIcon(imagenRedimensionada));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();

        javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/colbox-logo.png"));
    int ancho = 120; // smaller logo for minimal UI
    int alto = 80;
        java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);
        jLabel1.setIcon(new javax.swing.ImageIcon(imagenEscalada));

    // Accent color for active item
    final java.awt.Color accent = new java.awt.Color(0,153,204);

    // common style for nav buttons
    javax.swing.JButton[] navButtons = new javax.swing.JButton[5];

    jButton1.setBackground(new java.awt.Color(30, 30, 30));
    jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // smaller font for minimalist
    jButton1.setForeground(new java.awt.Color(220, 220, 220));
    jButton1.setText("Transacciones");
    jButton1.setBorder(null);
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActiveButton("transactions");
                jButton1ActionPerformed(evt);
            }
        });

    jButton2.setBackground(new java.awt.Color(30, 30, 30));
    jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jButton2.setForeground(new java.awt.Color(220, 220, 220));
    jButton2.setText("Productos");
    jButton2.setBorder(null);
    jButton2.setBorderPainted(false);
    jButton2.setContentAreaFilled(false);
    jButton2.setFocusPainted(false);
    jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActiveButton("products");
                jButton2ActionPerformed(evt);
            }
        });

    jButton3.setBackground(new java.awt.Color(30, 30, 30));
    jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jButton3.setForeground(new java.awt.Color(220, 220, 220));
    jButton3.setText("Productos (- stock)");
    jButton3.setBorder(null);
    jButton3.setBorderPainted(false);
    jButton3.setContentAreaFilled(false);
    jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActiveButton("products-low-stock");
                jButton3ActionPerformed(evt);
            }
        });

    jButton4.setBackground(new java.awt.Color(30, 30, 30));
    jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jButton4.setForeground(new java.awt.Color(220, 220, 220));
    jButton4.setText("Proveedor");
    jButton4.setBorder(null);
    jButton4.setBorderPainted(false);
    jButton4.setContentAreaFilled(false);
    jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActiveButton("providers");
                jButton4ActionPerformed(evt);
            }
        });

    jButton5.setBackground(new java.awt.Color(30, 30, 30));
    jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jButton5.setForeground(new java.awt.Color(220, 220, 220));
    jButton5.setText("Categoria");
    jButton5.setBorder(null);
    jButton5.setBorderPainted(false);
    jButton5.setContentAreaFilled(false);
    jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActiveButton("categories");
                jButton5ActionPerformed(evt);
            }
        });

    navButtons[0]=jButton1; navButtons[1]=jButton2; navButtons[2]=jButton3; navButtons[3]=jButton4; navButtons[4]=jButton5;


        // Logout button at the bottom
    jButtonLogout.setBackground(new java.awt.Color(40,40,40));
    jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 14));
    jButtonLogout.setForeground(new java.awt.Color(220,220,220));
    jButtonLogout.setText("Cerrar sesión");
    jButtonLogout.setBorder(null);
    jButtonLogout.setContentAreaFilled(false);
    jButtonLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    // removed select
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12,12,12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (navigationListener != null) navigationListener.navigateTo("products");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (navigationListener != null) navigationListener.navigateTo("products-low-stock");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if (navigationListener != null) navigationListener.navigateTo("categories");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if (navigationListener != null) navigationListener.navigateTo("providers");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (navigationListener != null) navigationListener.navigateTo("transactions");
    }//GEN-LAST:event_jButton1ActionPerformed

    // select removed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        if (navigationListener != null) {
            navigationListener.navigateTo("logout");
        } else {
            // default behaviour: confirm and close app
            int resp = javax.swing.JOptionPane.showConfirmDialog(this, "¿Cerrar sesión?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
            if (resp == javax.swing.JOptionPane.YES_OPTION) {
                java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
                if (w != null) w.dispose();
            }
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    // helper to style the active button
    private void setActiveButton(String route) {
        java.awt.Color accent = new java.awt.Color(0,153,204);
        // reset all
        javax.swing.JButton[] all = new javax.swing.JButton[]{jButton1,jButton2,jButton3,jButton4,jButton5};
        for (javax.swing.JButton b : all) {
            b.setForeground(new java.awt.Color(255,255,255));
            b.setFont(b.getFont().deriveFont(java.awt.Font.PLAIN));
        }
        switch(route) {
            case "products": jButton2.setForeground(accent); jButton2.setFont(jButton2.getFont().deriveFont(java.awt.Font.BOLD)); break;
            case "products-low-stock": jButton3.setForeground(accent); jButton3.setFont(jButton3.getFont().deriveFont(java.awt.Font.BOLD)); break;
            case "categories": jButton5.setForeground(accent); jButton5.setFont(jButton5.getFont().deriveFont(java.awt.Font.BOLD)); break;
            case "providers": jButton4.setForeground(accent); jButton4.setFont(jButton4.getFont().deriveFont(java.awt.Font.BOLD)); break;
            case "transactions": jButton1.setForeground(accent); jButton1.setFont(jButton1.getFont().deriveFont(java.awt.Font.BOLD)); break;
        }
    }

    // install simple hover effect on a button
    private void installHover(final javax.swing.JButton btn) {
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setForeground(new java.awt.Color(180,180,180));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // keep active or default
                // if any button is active, leave accent; else default
                btn.setForeground(new java.awt.Color(220,220,220));
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // javax.swing.JComboBox<String> jComboBox1; removed
    private javax.swing.JButton jButtonLogout;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        Area area = new Area(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.fill(area);
        g2.dispose();
        super.paint(grphcs);
    }
}
